[package]
name = "_server_routes"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
_types = { path = "../../../lib/types" }
_resources = { path = "../../../lib/resources" }
_server_database = { path = "../database" }
_server_functions = { path = "../functions" }
_client_view = { path = "../../client/view" }

hikari-boot = { workspace = true }
tairitsu-database = { workspace = true }

anyhow = { workspace = true }
async-trait = { workspace = true }
derive_more = { workspace = true }
once_cell = { workspace = true }
cfg-if = { workspace = true }

base64 = { workspace = true }
bytes = { workspace = true }
percent-encoding = { workspace = true }
chrono = { workspace = true }

tracing = { workspace = true }
futures = { workspace = true }
oneshot = { workspace = true }

serde = { workspace = true }
serde_json = { workspace = true }
toml = { workspace = true }
postcard = { workspace = true }
strum = { workspace = true }
uuid = { workspace = true }

sea-orm = { workspace = true }
axum = { workspace = true }
axum-extra = { workspace = true }

worker = { workspace = true, optional = true }

[features]
default = []
tokio = []

cloudflare = [
    "dep:worker",
    "tairitsu-database/cloudflare",
    "_server_functions/cloudflare",
]
native = ["tokio", "tairitsu-database/native", "_server_functions/native"]
wasi = ["tairitsu-database/wasi", "_server_functions/wasi"]
